import bpy
from bpy.app import translations as bpy_translations

iface_ = bpy_translations.pgettext_iface
tip_ = bpy_translations.pgettext_tip
rpt_ = getattr(bpy_translations, "pgettext_rpt", tip_)
i18n_contexts = bpy_translations.contexts


_TRANSLATIONS_ZH_TO_EN_BASE = {
    "物体插槽": "Object Socket",
    "SSMT蓝图": "SSMT Blueprint",
    "生成Mod": "Generate Mod",
    "根据当前工作空间对应的蓝图架构生成对应的Mod文件": "Generate the Mod files that match the current workspace blueprint.",
    "生成Mod成功！": "Generate Mod Success!",
    "打开蓝图界面": "Open Blueprint",
    "打开一个独立的蓝图窗口，用于配置Mod逻辑": "Open a standalone blueprint window for configuring Mod logic.",
    "选择对象": "Select Object",
    "选取对象": "Pick Object",
    "物体信息": "Object Info",
    "将所选物体新建到组节点": "Create Group from Selected Objects",
    "创建内部切换": "Create Internal Switch",
    "分组": "Group",
    "添加插槽": "Add Socket",
    "移除插槽": "Remove Socket",
    "按键切换": "Switch Key",
    "查看组内物体": "View Group Objects",
    "查看递归解析预览": "Preview Recursive Objects",
    "框架": "Frame",
    "SSMT蓝图架构": "SSMT Blueprint Graph",
    "形态键": "Shape Key",
    "形态键名称": "Shape Key Name",
    "按键": "Key",
    "按键名称": "Key Name",
    "变量别名": "Variable Alias",
    "名称": "Name",
    "备注": "Comment",
    "输出": "Output",
    "对象": "Object",
    "输入 1": "Input 1",
    "输入 {count}": "Input {count}",
    "状态 0": "Status 0",
    "状态 {count}": "Status {count}",
    "组 1": "Group 1",
    "组 {count}": "Group {count}",
    "DrawIB: ": "DrawIB: ",
    "IndexCount: ": "IndexCount: ",
    "FirstIndex: ": "FirstIndex: ",
    "别名: ": "Alias: ",
    "生成形态键Buffer": "Generate ShapeKey Buffer",
    "检测到该节点时，生成形态键Mod": "When this node is present, generate the Shape Key Mod.",
    "生成Mod面板": "Generate Mod Panel",
    "流光边框效果": "Flowing Border Effect",
    "勾选后，生成的Mod面板启用流光边框效果": "Enable the flowing border effect for the generated Mod panel.",
    "检测到该节点时生成Mod面板": "When this node is present, generate the Mod panel.",
    "流光效果": "Flow Effect",
    "没有选中的对象！": "No objects selected.",
    "没有选择任何物体": "No objects selected",
    "列表中未选择任何图片。": "No image selected in the list.",
    "已将 {image_name} 应用到 {count} 个物体。": "Applied {image_name} to {count} object(s).",
    "已扫描 {count} 张图片。": "Scanned {count} images.",
    "已自动检测并从 DedupedTextures_jpg 文件夹加载 {count} 张图片。": "Auto-detected and loaded {count} images from DedupedTextures_jpg folder.",
    "未找到当前蓝图，请在蓝图编辑器中点击“生成Mod”": "Current blueprint not found. Please click 'Generate Mod' in the blueprint editor.",
    "已选中对象: {name}": "Selected object: {name}",
    "已选择物体: {name}": "Picked object: {name}",
    "未找到对象": "Object not found",
    "未找到3D视图": "No 3D View found",
    "已退出局部视图": "Exited local view",
    "该分组中未找到任何物体": "No objects found in this group",
    "已在局部视图中显示 {count} 个物体": "Showing {count} objects in local view",
    "未找到有效的蓝图树，请先打开蓝图编辑器": "No valid blueprint tree found. Please open the blueprint editor first.",
    ("*", "以下物体没有序列号: {names}"): "These objects do not have sequence numbers: {names}",
    ("*", "没有找到带序列号的物体"): "No objects with sequence numbers were found",
    ("*", "已创建 {count} 个物体节点并连接到切换节点"): "Created {count} object nodes and connected them to the switch node",
    ("*", "矩阵对齐节点"): "Align Nodes in Grid",
    ("*", "批量连接节点"): "Batch Connect Nodes",
    ("*", "请在节点编辑器中使用此功能"): "Please use this feature in the node editor",
    ("*", "未找到节点树"): "Node tree not found",
    ("*", "请至少选择2个节点"): "Please select at least 2 nodes",
    ("*", "已将 {node_count} 个节点结构化对齐，分为 {column_count} 列"): "Aligned {node_count} nodes into a structured layout with {column_count} columns",
    ("*", "所选节点类型过多（{count}种），请选择1-2种类型的节点"): "Too many selected node types ({count}). Please select 1 or 2 types of nodes.",
    ("*", "所选节点类型相同，无法连接"): "The selected nodes are the same type and cannot be connected",
    ("*", "无法确定连接方向，请检查节点端口配置"): "Cannot determine connection direction. Please check the node socket configuration.",
    ("*", "节点 '{node_name}' 没有输入端口"): "Node '{node_name}' has no input socket",
    ("*", "节点 '{node_name}' 没有可用的输入端口"): "Node '{node_name}' has no available input socket",
    ("*", "一对一连接：成功连接 {count} 个节点对"): "One-to-one connection: successfully connected {count} node pairs",
    ("*", "多数节点 '{node_name}' 没有输出端口"): "Majority node '{node_name}' has no output socket",
    ("*", "少数节点 '{node_name}' 没有输入端口"): "Minority node '{node_name}' has no input socket",
    ("*", "多对一连接：成功连接 {count} 个节点对"): "Many-to-one connection: successfully connected {count} node pairs",
    ("*", "刷新物体节点信息"): "Refresh Object Node Info",
    ("*", "刷新 Submesh 列表"): "Refresh Submesh List",
    ("*", "批量设为指定Submesh"): "Batch Set Selected Nodes to Submesh",
    ("*", "所属Submesh"): "Submesh",
    ("*", "Submesh"): "Submesh",
    ("*", "目标 Submesh"): "Target Submesh",
    ("*", "当前 Submesh 不在列表中，导出时将回退到物体名解析"): "The current submesh is not in the list. Export will fall back to parsing the object name.",
    ("*", "已刷新当前蓝图的 Submesh 列表，共 {count} 项"): "Refreshed the current blueprint submesh list with {count} entries",
    ("*", "请选择一个有效的 Submesh"): "Please choose a valid submesh",
    ("*", "当前未选中任何物体节点"): "No object info nodes are currently selected",
    ("*", "已将 {count} 个物体节点设为 Submesh: {submesh}"): "Set {count} object info nodes to submesh: {submesh}",
    ("*", "已刷新 {updated_count} 个物体节点，另有 {missing_count} 个节点未找到对应物体，耗时 {elapsed_ms:.3f} ms"): "Refreshed {updated_count} object nodes, {missing_count} nodes could not find their objects, took {elapsed_ms:.3f} ms",
    ("*", "已刷新 {updated_count} 个物体节点，耗时 {elapsed_ms:.3f} ms"): "Refreshed {updated_count} object nodes, took {elapsed_ms:.3f} ms",
    ("*", "所有物体节点都已是最新状态，耗时 {elapsed_ms:.3f} ms"): "All object nodes are already up to date, took {elapsed_ms:.3f} ms",
    ("*", "点击后在3D视图中选择一个物体"): "Click to pick an object in the 3D View",
    ("*", "无法获取节点树上下文"): "Cannot get node tree context",
    ("*", "请在3D视图中点击选择一个物体"): "Please click an object in the 3D View",
    ("*", "请在3D视图中点击选择一个物体..."): "Please click an object in the 3D View...",
    ("*", "当前生成Mod位置文件夹:"): "Current Generate Mod Folder:",
    ("*", "返回上一层级"): "Back to Previous Level",
    ("*", "请选择有效的文件夹"): "Please select a valid folder",
    ("*", "生成Mod文件夹已设置为: {path}"): "Generate Mod folder set to: {path}",
    ("*", "禁止自动贴图流程"): "Disable Auto Texture Workflow",
    ("*", "向量归一化法线存入TANGENT(全局)"): "Store Vector-Normalized Normals in TANGENT (Global)",
    ("*", "算术平均归一化法线存入COLOR(全局)"): "Store Arithmetic-Average Normals in COLOR (Global)",
    ("*", "生成Mod后打开Mod所在文件夹"): "Open Mod Folder After Generating Mod",
    ("*", "基础信息面板"): "Basic Information Panel",
    ("*", "SSMT缓存文件夹路径: "): "SSMT Cache Folder: ",
    ("*", "当前配置名称: "): "Current Config Name: ",
    ("*", "当前游戏预设: "): "Current Game Preset: ",
    ("*", "当前工作空间: "): "Current Workspace: ",
    "生成后打开Mod文件夹": "Open Mod Folder After Generation",
    "勾选后，在生成Mod完成后自动打开Mod文件夹": "When enabled, automatically open the Mod folder after generation completes.",
    "槽位风格贴图使用SlotFix技术": "Use SlotFix for Slot-Style Textures",
    "仅适用于槽位风格贴图，勾选后，特定名称标记的贴图将使用SlotFix风格，能一定程度上解决槽位风格贴图跨槽位的问题，跨Pixel槽位指的是在前一个DrawCall中是ps-t3但是下一个DrawCall变为ps-t5这种情况，但由于负责维护的人也在偷懒所以并不可靠": "Only applies to slot-style textures. When enabled, textures with specific name markers will use the SlotFix style, which can partially mitigate issues caused by textures crossing slots. Crossing pixel slots means a texture is ps-t3 in one DrawCall but becomes ps-t5 in the next. However, this solution is not fully reliable.",
    "槽位风格贴图使用ORFix": "Use ORFix for Slot-Style Textures",
    "勾选后，在使用槽位风格贴图标记时，如果偷懒不想手动维护由于贴图槽位变化导致的贴图损坏问题，可以勾选此选项将问题交给ORFix维护者来解决，仅GIMI可用\n注意，如果你不懂ORFix和NNFix的原理，请不要取消勾选，取消勾选会严格按照贴图标记来执行贴图部分ini生成，默认你会在ini中自行写判断语句修复来替代实现ORFix和NNFix的功能": "When enabled, if you do not want to manually maintain texture issues caused by slot changes while using slot-style texture markers, you can leave this to ORFix. Available only for GIMI.\nNote: if you do not understand how ORFix and NNFix work, do not disable this option. Disabling it will generate the texture-related INI strictly according to the texture markers, assuming you will write your own conditional fixes in the INI instead.",
    "生成分支切换Mod面板(测试版)": "Generate Branch Switch Mod Panel (Test)",
    "生成Mod时，生成一个基于当前集合架构的分支Mod面板，可在游戏中按住Ctrl + Alt呼出，仍在测试改进中": "When generating a Mod, also generate a branch-based Mod panel according to the current collection structure. It can be opened in-game by holding Ctrl + Alt. This feature is still under testing and improvement.",
    "生成Mod时禁止生成贴图相关ini部分": "Do not generate the texture-related INI sections when generating the Mod.",
    "使用向量相加归一化重计算所有模型的TANGENT值，勾选此项后无法精细控制具体某个模型是否计算，是偷懒选项,在不勾选时默认使用右键菜单中标记的选项。\n用途:\n1.一般用于修复GI角色,HI3 1.0角色,HSR角色轮廓线。\n2.用于修复模型由于TANGENT不正确导致的黑色色块儿问题，比如HSR的薄裙子可能会出现此问题。": "Recalculate TANGENT for all models using vector-sum normalization. After enabling this option, you can no longer control per-model recalculation precisely. This is a convenience option. When disabled, the option marked in the right-click menu is used by default.\nUses:\n1. Commonly used to fix outlines for GI characters, HI3 1.0 characters, and HSR characters.\n2. Used to fix black artifact issues caused by incorrect TANGENT data, such as on thin skirts in HSR.",
    "使用算术平均归一化重计算所有模型的COLOR值，勾选此项后无法精细控制具体某个模型是否计算，是偷懒选项,在不勾选时默认使用右键菜单中标记的选项，仅用于HI3 2.0角色修复轮廓线": "Recalculate COLOR for all models using arithmetic-average normalization. After enabling this option, you can no longer control per-model recalculation precisely. This is a convenience option. When disabled, the option marked in the right-click menu is used by default. Used only for fixing outlines on HI3 2.0 characters.",
    "生成Mod到指定的文件夹中": "Generate Mod to a Specific Folder",
    "勾选后将生成Mod到你指定的文件夹中": "When enabled, generate the Mod into the folder you specify.",
    "生成Mod文件夹路径": "Generate Mod Folder Path",
    "选择的生成Mod的文件夹路径": "The selected folder path for generated Mods.",
    ("*", "使用非镜像工作流"): "Use Non-Mirrored Workflow",
    "默认为False, 启用后导入和导出模型将不再是镜像的，目前3Dmigoto的模型导入后是镜像存粹是由于历史遗留问题是错误的，但是当错误积累成粑粑山，人的习惯和旧的工程很难被改变，所以只有勾选后才能使用非镜像工作流": "Default is False. When enabled, imported and exported models will no longer be mirrored. The current mirrored behavior in 3Dmigoto imports is a legacy mistake, but old habits and existing projects make it hard to change by default, so non-mirrored workflow is only used when this option is enabled.",
    "自动上贴图时使用法线贴图": "Use Normal Maps During Auto Texture Assignment",
    "启用后在导入模型时自动附加法线贴图节点, 在材质预览模式下得到略微更好的视觉效果": "When enabled, automatically attach a normal map node when importing models to get slightly better visual results in material preview mode.",
    "顶点组模式": "Vertex Group Mode",

    "忽略未启用的形态键": "Ignore Disabled Shape Keys",
    "勾选此项后，未勾选启用的形态键在生成Mod时会被忽略，勾选的形态键会参与生成Mod": "When enabled, shape keys that are not checked will be ignored during Mod generation, and only checked shape keys will be included.",
    "应用所有修改器": "Apply All Modifiers",
    "勾选此项后，生成Mod之前会自动对物体应用所有修改器": "When enabled, all modifiers on objects will be applied automatically before generating the Mod.",
    "跳过空顶点组": "Skip Empty Vertex Groups",
    "勾选此项后，导入时会跳过空的顶点组": "When enabled, empty vertex groups will be skipped during import.",
    "导出时添加缺失顶点组": "Add Missing Vertex Groups During Export",
    "勾选此项后，生成Mod时会自动重新排列并填补数字顶点组间的间隙空缺": "When enabled, numeric vertex groups will be automatically reordered and missing gaps will be filled during Mod generation.",
    ("*", "游戏类型: "): "Game Type: ",
    ("*", "重计算TANGENT: "): "Recalculate TANGENT: ",
    ("*", "重计算COLOR: "): "Recalculate COLOR: ",
    ("*", "一键导入SSMT工作空间内容"): "Import All From SSMT Workspace",
    ("*", "一键导入当前工作空间文件夹下所有的内容"): "Import everything from the current workspace folder with one click.",
    ("*", "导入SSMT格式模型"): "Import SSMT Model",
    ("*", "导入SSMT格式的模型文件, 只需选择.json文件即可"): "Import an SSMT model file. You only need to select the .json file.",
    ("*", "请先在SSMT中选择当前工作空间后再导入。") : "Please select the current workspace in SSMT before importing.",
    ("*", "工作空间文件夹不存在，请先在SSMT中创建工作空间: {path}"): "Workspace folder does not exist. Please create a workspace in SSMT first: {path}",
    ("*", "读取DedupedTextures"): "Load DedupedTextures",
    ("*", "读取当前Component专属贴图"): "Load Current Component Textures",
    ("*", "未找到当前DrawIB: {draw_ib}的DedupedTextures转换后的贴图文件夹，请确保此IB在当前工作空间中已经正常提取出来了"): "Could not find the converted DedupedTextures folder for DrawIB {draw_ib}. Please make sure this IB has been extracted correctly in the current workspace.",
    ("*", "选择预览贴图所在的文件夹位置"): "Select Preview Texture Folder",
    "自动检测提取的贴图文件夹": "Auto Detect Extracted Texture Folder",
    ("*", "应用贴图到选中的物体"): "Apply Texture to Selected Objects",
    ("*", "快速上预览贴图"): "Quick Preview Texture",
    ("*", "图片名称"): "Image Name",
    ("*", "文件路径"): "File Path",
    ("*", "图片列表"): "Image List",
    ("*", "已找到 {count} 张图片"): "Found {count} images",
    ("*", "未找到图片，请先选择文件夹。") : "No images found. Select a folder first.",
    ("*", "预览:"): "Preview:",
    ("*", "您当前选中的物体命名不符合SSMT模型制作规范: DrawIB-Component数-自定义名称，无法自动识别可用的贴图列表"): "The selected object's name does not follow the SSMT naming convention: DrawIB-Component-CustomName, so the texture list cannot be detected automatically.",
    ("*", "一键导入逆向出来的全部模型"): "Import All Reversed Models",
    ("*", "把上一次一键逆向出来的所有模型全部导入到Blender，然后你可以手动筛选并删除错误的数据类型，流程上更加方便。"): "Import all models generated by the last reverse pass into Blender, then manually filter and delete incorrect data types for a smoother workflow.",
    ("*", "当前一键逆向结果中标注的文件夹位置不存在，请重新运行一键逆向"): "The folder recorded for the latest reverse result does not exist. Please run reverse again.",
    ("*", "导入.fmt .ib .vb格式模型"): "Import .fmt .ib .vb Model",
    ("*", "导入3Dmigoto格式的 .ib .vb .fmt文件，只需选择.fmt文件即可"): "Import 3Dmigoto .ib .vb .fmt files. You only need to select the .fmt file.",
    ("*", "3Dmigoto-Sword面板"): "3Dmigoto Sword Panel",
    "手动逆向后根据DrawIndexed值分割模型": "Split Model by DrawIndexed After Manual Reverse",
    "根据UV松散块儿分割模型": "Split Model by UV Loose Parts",
    "模型处理面板": "Model Processing Panel",
    "适用于3Dmigoto Mod制作的常用功能": "Common features for making 3Dmigoto Mods.",
    ("*", "功能与Edit界面的Split => Split by Loose Parts相似，但是分割模型为松散块儿并放入新集合。"): "Similar to Edit > Split > Split by Loose Parts, but splits the model into loose parts and puts them into a new collection.",
    ("*", "根据共享与孤立顶点组分割模型"): "Split Model by Shared and Isolated Vertex Groups",
    ("*", "把模型根据共享的顶点组分开，方便快速分离身体上的小物件，方便后续刷权重不受小物件影响。") : "Split the model by shared vertex groups to quickly separate small attachments and avoid affecting later weight painting.",
    ("*", "删除模型中的松散点"): "Delete Loose Points",
    ("*", "删除模型中的松散点，避免影响后续的模型处理。"): "Delete loose points in the model to avoid affecting later processing.",
    ("*", "清除自定义拆分法向"): "Clear Custom Split Normals",
    ("*", "WWMI 逆向得到的模型，有时顶点法线会歪，用这个处理一下就行。"): "Models reversed from WWMI sometimes have skewed vertex normals. Use this to fix them.",
    ("*", "用模型名称作为前缀重命名顶点组"): "Rename Vertex Groups with Model Name Prefix",
    ("*", "用模型名称作为前缀重命名顶点组，方便后续合并到一个物体后同名称的顶点组不会合在一起冲突，便于后续一键绑定骨骼。") : "Rename vertex groups with the model name as a prefix so groups with the same name do not conflict after merging into one object.",
    ("*", "移除所有顶点组"): "Remove All Vertex Groups",
    ("*", "移除当前选中obj的所有顶点组"): "Remove all vertex groups from the selected object.",
    ("*", "移除未使用的空顶点组"): "Remove Unused Empty Vertex Groups",
    ("*", "移除当前选中obj的所有空顶点组，也就是移除未使用的顶点组"): "Remove all empty vertex groups from the selected object, that is, remove unused vertex groups.",
    ("*", "合并具有相同数字前缀名称的顶点组"): "Merge Vertex Groups with the Same Numeric Prefix",
    ("*", "把当前选中obj的所有数字前缀名称相同的顶点组进行合并"): "Merge all vertex groups on the selected object that share the same numeric prefix.",
    ("*", "填充数字顶点组的间隙"): "Fill Numeric Vertex Group Gaps",
    ("*", "把当前选中obj的所有数字顶点组的间隙用数字命名的空顶点组填补上，比如有顶点组1,2,5,8则填补后得到1,2,3,4,5,6,7,8"): "Fill numeric vertex group gaps on the selected object with empty numbered vertex groups. For example, 1,2,5,8 becomes 1,2,3,4,5,6,7,8.",
    ("*", "根据顶点组生成基础骨骼"): "Generate Basic Bones from Vertex Groups",
    ("*", "把当前选中的obj的每个顶点组都生成一个默认位置的骨骼，方便接下来手动调整骨骼位置和父级关系来绑骨，虹汐哥改进版本"): "Generate a bone at a default position for each vertex group on the selected object, making it easier to adjust bones manually and bind later.",
    ("*", "移除非数字名称的顶点组"): "Remove Non-Numeric Vertex Groups",
    ("*", "把当前选中的obj的所有不是纯数字命名的顶点组都移除"): "Remove all vertex groups on the selected object that are not named with pure numbers.",
    ("*", "根据顶点组将模型打碎为松散块儿"): "Break Model into Loose Parts by Vertex Groups",
    ("*", "把当前选中的obj按顶点组进行分割，适用于部分精细刷权重并重新组合模型的场景"): "Split the selected object by vertex groups. Useful for precise weight painting and recombining models.",
    ("*", "按顶点组分割模型"): "Split Model by Vertex Group",
    ("*", "把当前选中的obj按每个顶点组分割为独立网格，保留所有属性（UV、权重、颜色、法线、形态键等），结果放入'{obj名}_Split'集合"): "Split the selected object into individual meshes by each vertex group, preserving all attributes (UVs, weights, colors, normals, shape keys, etc.). Results go into '{obj_name}_Split' collection.",
    ("*", "根据松散块儿分割并聚类"): "Split by Loose Parts and Cluster",
    ("*", "按松散块儿分割后，将 VG 集合近似（Jaccard 相似度）且空间邻接的松散块儿合并为一个部位，结果放入'{obj名}_SplitCluster'集合"): "Split by loose parts, then merge spatially adjacent parts with similar VG sets (Jaccard similarity). Results go into '{obj_name}_SplitCluster' collection.",
    ("*", "VG 相似度阈值"): "VG Similarity Threshold",
    ("*", "Jaccard 相似度（交集/并集），两个松散块儿的 VG 集合相似度 >= 此值且空间邻接时合并"): "Jaccard similarity (intersection/union). Parts with VG similarity >= this value and spatially adjacent will be merged.",
    ("*", "包围盒距离阈值"): "BBox Distance Threshold",
    ("*", "两个松散块儿的包围盒距离 <= 此值时视为空间邻接"): "Two loose parts are considered spatially adjacent when their bounding box distance <= this value.",
    ("*", "重置模型x,y,z的旋转角度为0"): "Reset Model Rotation on X, Y, Z to 0",
    ("*", "把当前选中的obj的x,y,z的旋转角度全部归0"): "Reset the selected object's X, Y, and Z rotation to 0.",
    ("*", "平滑法线存UV(近似)"): "Store Smooth Normals in UV (Approximate)",
    ("*", "平滑法线存UV算法，可用于修复ZZZ,WWMI的某些UV(只是近似实现60%的效果)"): "Store smooth normals in UV. Can be used to fix some UV issues in ZZZ and WWMI, though the effect is approximate.",
    ("*", "在有形态键的模型上应用修改器"): "Apply Modifiers on a Model with Shape Keys",
    ("*", "在带有形态键的模型上应用选中的修改器，并将其从堆栈中移除，用于解决“带形态键的网格无法应用修改器”的问题。"): "Apply selected modifiers on a model with shape keys and remove them from the stack to solve the issue where modifiers cannot be applied to a mesh with shape keys.",
    ("*", "不包含骨架变形"): "Don't Include Armature Deformations",
    ("*", "警告:"): "Warning:",
    ("*", "该物体的形态键包含动画数据"): "This object's shape keys contain animation data.",
    ("*", "（例如驱动、关键帧等）"): "(such as drivers, keyframes, etc.)",
    ("*", "应用修改器后这些数据会丢失！"): "These data will be lost after applying modifiers!",
    ("*", "未选择任何修改器！"): "No modifier selected!",
    ("*", "使用向量相加归一化算法重计算TANGENT"): "Recalculate TANGENT with Vector-Sum Normalization",
    ("*", "近似修复轮廓线算法，可以达到99%的轮廓线相似度，适用于GI,HSR,ZZZ,HI3 2.0之前的老角色"): "An approximate outline-fix algorithm that can reach 99% outline similarity. Suitable for GI, HSR, ZZZ, and older HI3 characters before 2.0.",
    ("*", "使用算术平均归一化算法重计算COLOR"): "Recalculate COLOR with Arithmetic-Average Normalization",
    ("*", "近似修复轮廓线算法，可以达到99%的轮廓线相似度，仅适用于HI3 2.0新角色"): "An approximate outline-fix algorithm that can reach 99% outline similarity. Suitable only for new HI3 2.0 characters.",
    ("*", "重命名选中Amature的骨骼名称(GI)(测试)"): "Rename Bones of Selected Armature (GI) (Test)",
    ("*", "用于把游戏里解包出来的骨骼重命名，方便我们直接一键绑定到提取出的Mod模型上，感谢 Leotorrez。"): "Rename bones unpacked from the game so they can be bound to extracted Mod models more easily. Thanks to Leotorrez.",
    ("*", "重置模型在x,y,z轴上的位置为0"): "Reset Model Location on X, Y, Z to 0",
    ("*", "把当前选中的obj的x,y,z轴上的位置全部重置为0，使模型回到坐标原点"): "Reset the selected object's X, Y, and Z location to 0 so the model returns to the origin.",
    ("*", "根据顶点组名称对顶点组进行排序"): "Sort Vertex Groups by Name",
    ("*", "和Blender顶点组权重那里自带的Sort=>By Name功能一样，放在这里方便快速调用"): "The same as Blender's built-in Sort > By Name for vertex groups, placed here for quick access.",
    ("*", "将目标obj的顶点组按位置对应关系改名"): "Rename Target Object Vertex Groups by Positional Mapping",
    ("*", "先选中一个源obj，再选中一个目标obj，再点击此按钮，会根据顶点组对应位置把目标obj的顶点组改名为源obj的顶点组名称，目标obj的顶点组中，和源obj顶点组位置相近的顶点组将被改名为源obj对应位置的顶点组的名称，未能识别的顶点组将被命名为unknown"): "First select a source object, then a target object, and click this button. Vertex groups on the target object will be renamed to match source vertex groups based on positional correspondence. Unmatched groups will be named 'unknown'.",
    ("*", "根据DrawIndexed值分割模型"): "Split Model by DrawIndexed Values",
    ("*", "起始索引"): "Start Index",
    ("*", "索引缓冲区中的起始索引"): "Starting index in the index buffer",
    ("*", "索引数量"): "Index Count",
    ("*", "要包含的索引数量，必须是 3 的倍数"): "Number of indices to include. Must be a multiple of 3.",
    ("*", "请选择一个网格对象"): "Select a mesh object",
    ("*", "索引范围超出缓冲区，最大 loop 数量为: {count}"): "Index range exceeds buffer. Maximum loop count: {count}",
    "索引数量必须是 3 的倍数": "Index count must be a multiple of 3",
}


_TRANSLATION_CONTEXTS = (
    i18n_contexts.default,
    i18n_contexts.operator_default,
    i18n_contexts.id_windowmanager,
)


def _build_contextual_translations(base_mapping):
    contextual_mapping = {}
    for source_key, translated_text in base_mapping.items():
        if isinstance(source_key, tuple):
            _, source_text = source_key
        else:
            source_text = source_key
        for context_name in _TRANSLATION_CONTEXTS:
            contextual_mapping[(context_name, source_text)] = translated_text
    return contextual_mapping


_TRANSLATIONS_ZH_TO_EN = _build_contextual_translations(_TRANSLATIONS_ZH_TO_EN_BASE)


translations_dict = {
    "en_US": _TRANSLATIONS_ZH_TO_EN,
    "en_GB": _TRANSLATIONS_ZH_TO_EN,
}


def register():
    try:
        bpy.app.translations.unregister(__name__)
    except (ValueError, RuntimeError):
        pass
    bpy.app.translations.register(__name__, translations_dict)


def unregister():
    try:
        bpy.app.translations.unregister(__name__)
    except (ValueError, RuntimeError):
        pass


